config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    resources :sessions
    resources :lessions  do
      collection do
        get :search
      end
    end
    resources :users
    resources :tests do
      member do
        get  :start, :result
        post :finnish
      end
    end
    resources :sentences, only: [:update]
    resources :staticpage, only: [:index]
  end

  root "customer/staticpage#index"
  get   'login'   => 'sessions#new'
  resources :sessions
  namespace :admin do
    resources :categories
    resources :lessions
    resources :quessions do
      collection do
        get :import_csv
      end
    end
    resources :staticpage, only: [:index]
  end

end

app/models/lession.rb
class Lession < ActiveRecord::Base
  belongs_to :category
  has_many :quessions, dependent: :destroy

  validates :content, presence: true , length: { maximum: Settings.max_content },
    uniqueness: { case_sensitive: false }

  def self.search(condition_search = '')
    if "".eql?(condition_search)
      return Lession.all
    else
      return Lession.where("content like ?", "%#{condition_search}%")
    end
  end
end

app/controllers/admin/lessions_controller.rb
class Admin::LessionsController < ApplicationController
  layout "admin"
  def index
    @lessions= Lession.paginate(page: params[:page])
  end

  def new
    @categories = Category.all
    @lession = Lession.new
  end

  def create
    @lession = Lession.new(lession_params)
    if @lession.save
      flash[:success] = "lession created!"
      redirect_to action: :index
    else
      flash[:danger] = "lession is unvalid!"
      render action: :new
    end
  end

  def edit
    @categories = Category.all
    @lession = Lession.find_by(id: params[:id])
  end

  def update
    @lession = Lession.find_by(id: params[:id])
    if @lession.update_attributes(lession_params)
      flash[:success] = "update lession success!!!"
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @lession = Lession.find_by(id: params[:id])
    @lession.destroy
    flash[:success]=  "delete lession success!!!"
    redirect_to request.referrer || root_url
  end

  private
  def lession_params
    params.require(:lession).permit(:name, :category_id, :content)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.is_admin?
  end
end

app/controllers/customer/lessions_controller.rb
class Customer::LessionsController < ApplicationController
  def show
    @lession = Lession.find(params[:id])
  end
  def search
    if !params[:search_form].nil?
      @lessions = Lession.search(params[:search_form][:condition])
    else
      @words = Word.search
    end
    respond_to do |format|
      format.html { render 'search' }
      format.js
    end
  end
end

app/helpers/admin/lessions_helper.rb
module Admin::LessionsHelper
end

app/helpers/customer/lessions_helper.rb
module Customer::LessionsHelper
end

app/views/admin/lessions/edit.html.erb
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lessions <small>edit</small></h2>
                   <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <%= form_for(@lession, url: admin_lession_path, html: {class:
                        "form-horizontal form-label-left"}) do |f| %>
                        <%= render 'shared/error_messages', object: f.object %>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Name <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :name, class: "form-control col-md-7 col-xs-12" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Name category <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.collection_select :category_id, @categories, :id,
                            :name, {}, {class: "form-control col-md-7 col-xs-12"} %>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Content <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.cktext_area :content, rows: 20 %>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <%= f.submit "Create", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
         </div>

app/views/admin/lessions/index.html.erb
<div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>All lessions <small>basic</small></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Name Lession</th>
                          <th>Name Category</th>
                          <th>Change</th>
                          <th>Delete</th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @lessions.each do |lession| %>
                        <tr>
                          <th scope="row"><%= lession.id %></th>
                          <td><%= lession.name %></td>
                          <td><%= lession.category.name %></td>
                          <td><%= link_to "edit", edit_admin_lession_path(lession),
                            method: :get, class: 'btn btn-default' %></td>
                          <td><%= link_to "delete", admin_lession_path(lession),
                            method: :delete, class: 'btn btn-danger',
                            data: { confirm: "You sure?" } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                    </table>
                  </div>
                </div>
                  <%= will_paginate @categories %>
              </div>
        </div>

app/views/admin/lessions/new.html.erb
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lessions <small>new</small></h2>
                   <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <%= form_for(@lession, url: admin_lessions_path, html: {class:
                        "form-horizontal form-label-left"}) do |f| %>
                        <%= render 'shared/error_messages', object: f.object %>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Name <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :name, class: "form-control col-md-7 col-xs-12" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Name category <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.collection_select :category_id, @categories, :id,
                            :name, {}, {class: "form-control col-md-7 col-xs-12"} %>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Content <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.cktext_area :content, rows: 20 %>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <%= f.submit "Create", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
         </div>