config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    resources :sessions
    resources :lessions  do
      collection do
        get :search
      end
    end
    resources :users
    resources :tests do
      member do
        get  :start, :result
        post :finnish
      end
    end
    resources :sentences, only: [:update]
    resources :staticpage, only: [:index]
  end

  root "customer/staticpage#index"
  get   'login'   => 'sessions#new'
  resources :sessions
  namespace :admin do
    resources :categories
    resources :lessions
    resources :quessions do
      collection do
        get :import_csv
      end
    end
    resources :staticpage, only: [:index]
  end

end

app/models/quession.rb
class Quession < ActiveRecord::Base
  belongs_to :lession

  # has_many :sentences, dependent: :destroy
  validates :lession, presence: true
  validates :content, presence: true

  has_many :answers , dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  # validates_associated :answers
  validate :must_have_correct_checked

  # def self.search(user_id, category_id = '' ,condition_search = '')
  #   lession_ids = "select id from lessions where user_id = #{user_id}"
  #   word_ids = "select word_id from quessions where lession_id in (#{lession_ids})"
  #   if "learned".eql?(condition_search)
  #     return ''.eql?(category_id) ? Word.where("id in (#{word_ids})") :
  #     Word.where("id in (#{word_ids}) and category_id = #{category_id}")
  #   elsif "unlearned".eql?(condition_search)
  #     return ''.eql?(category_id) ? Word.where("id not in (#{word_ids})") :
  #     Word.where("id not in (#{word_ids}) and category_id = #{category_id}")
  #   else
  #     return ''.eql?(category_id) ? Word.all : Word.where("category_id = #{category_id}")
  #   end
  # end

  def import file
       CSV.foreach(file.path, headers: true, col_sep: "|", header_converters: :symbol) do |row|
         row = row.to_hash
         answers_attributes = []
         row[:answers].split(";").each do |answer|
           answer_hash = Hash.new
           arr_answer = answer.split(",")
           answer_hash[:content] = arr_answer[0]
           answer_hash[:is_correct] = arr_answer[1]
           answers_attributes.push answer_hash
         end
         row[:answers_attributes] = answers_attributes
         row.delete :answers
         Question.create! row
       end
  end

  def meaning
    self.answers.each do |answer|
      if answer.is_correct
        return answer.content
      end
    end
    return "can't find"
  end

  private
    def must_have_correct_checked
      self.answers.each do |answer|
        if answer.is_correct
          return true
        end
      end
      errors.add(:is_correct,"must have correct answer!!!")
    end
end

app/controllers/admin/quessions_controller.rb
class Admin::QuessionsController < ApplicationController
  layout "admin"
  def index
    @quessions= Quession.paginate(page: params[:page])
  end

  def new
    @quession = Quession.new
    2.times { @quession.answers.build }
  end

  def create
    @quession = Quession.new(quession_params)
    if @quession.save
      flash[:success] = "quession created!"
      redirect_to action: :index
    else
      flash[:danger] = "quession is unvalid!"
      render action: :new
    end
  end

  def edit
    @lessions = Lession.all
    @quession = Quession.find_by(id: params[:id])
  end

  def update
    @quession = Quession.find_by(id: params[:id])
    if @quession.update_attributes(quession_params)
      flash[:success] = "update quession success!!!"
      redirect_to action: :index
    else
      render :edit
    end
  end

  def import_csv
     Question.import params[:file]
     redirect_to root_url, notice: "Question imported"
  end


  def destroy
    @quession = Quession.find_by(id: params[:id])
    byebug
    @quession.destroy
    flash[:success]=  "delete quession success!!!"
    redirect_to request.referrer || root_url
  end

  private
  def quession_params
    params.require(:quession).permit!
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.is_admin?
  end
end

app/helpers/admin/quessions_helper.rb
module Admin::QuessionsHelper
end

app/views/admin/quessions/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, 'is correct' %>
    <%= f.check_box :is_correct, style: 'width: auto' %>
  <%= f.text_field :content, class: 'form-control' %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "remove", '#', class: 'remove_answer'  %>
</fieldset>

<script type="text/javascript">
  $(".remove_answer").bind('click', function() {
    $(this).prev('input[type=hidden]').val(1);
    $(this).closest('fieldset').hide();
    event.preventDefault();
  });
</script>

app/views/admin/quessions/edit.html.erb
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Quession <small>edit</small></h2>
                   <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <%= form_for(@quession, url: admin_quession_path, html: {class:
                        "form-horizontal form-label-left"}) do |f| %>
                        <%= render 'shared/error_messages', object: f.object %>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Content <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :content, class: "form-control col-md-7 col-xs-12" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Lession <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.collection_select :lession_id, Lession.all, :id,
                            :name, {}, {class: "form-control col-md-7 col-xs-12"} %>
                        </div>
                      </div>
                      <div class="form-group">
                        <%= f.fields_for :answers do |builder| %>
                          <%= render 'answer_fields', f: builder %>
                        <% end %>
                      </div>
                      <%= link_to_add_fields "More answer", f, :answers %>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <%= f.submit "Update", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
         </div>
<script type="text/javascript">

  $(".add_fields").bind('click', function() {
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    event.preventDefault()
  });
</script>

app/views/admin/quessions/index.html.erb
<div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>All quessions <small>basic</small></h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Name Quession</th>
                          <th>Name Lession</th>
                          <th>Change</th>
                          <th>Delete</th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @quessions.each do |quession| %>
                        <tr>
                          <th scope="row"><%= quession.id %></th>
                          <td><%= quession.content %></td>
                          <td><%= quession.lession.name %></td>
                          <td><%= link_to "edit", edit_admin_quession_path(quession),
                            method: :get, class: 'btn btn-default' %></td>
                          <td><%= link_to "delete", admin_quession_path(quession),
                            method: :delete, class: 'btn btn-danger',
                            data: { confirm: "You sure?" } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                    </table>
                  </div>
                </div>
                  <%= will_paginate @quessions %>
              </div>
        </div>

app/views/admin/quessions/new.html.erb
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lessions <small>new</small></h2>
                   <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <%= form_for(@quession, url: admin_quessions_path, html: {class:
                        "form-horizontal form-label-left"}) do |f| %>
                        <%= render 'shared/error_messages', object: f.object %>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Content <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :content, class: "form-control col-md-7 col-xs-12" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >
                          Lession <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.collection_select :lession_id, Lession.all, :id,
                            :name, {}, {class: "form-control col-md-7 col-xs-12"} %>
                        </div>
                      </div>
                      <div class="form-group">
                        <%= f.fields_for :answers do |builder| %>
                          <%= render 'answer_fields', f: builder %>
                        <% end %>
                      </div>
                      <%= link_to_add_fields "More answer", f, :answers %>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <%= f.submit "Create", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
         </div>
<script type="text/javascript">

  $(".add_fields").bind('click', function() {
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    event.preventDefault()
  });
</script>