config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    resources :sessions
    resources :lessions  do
      collection do
        get :search
      end
    end
    resources :users
    resources :tests do
      member do
        get  :start, :result
        post :finnish
      end
    end
    resources :sentences, only: [:update]
    resources :staticpage, only: [:index]
  end

  root "customer/staticpage#index"
  get   'login'   => 'sessions#new'
  resources :sessions
  namespace :admin do
    resources :categories
    resources :lessions
    resources :quessions do
      collection do
        get :import_csv
      end
    end
    resources :staticpage, only: [:index]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessions, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.max_name}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"
  def index
     @categories= Category.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created!"
      redirect_to action: :index
    else
      flash[:danger] = "Category is unvalid!"
      render action: :new
    end
  end


  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find_by(id: params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "update category success!!!"
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy
    flash[:success]=  "delete category success!!!"
    redirect_to request.referrer || root_url
  end


  private
  def category_params
    params.require(:category).permit(:name)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.is_admin?
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Category <small>change</small></h2>
                   <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <%= form_for(@category, url: admin_lession_path, html: {class: "form-horizontal form-label-left"}) do |f| %>
                      <%= render 'shared/error_messages', object: f.object %>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >Name <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :name, class: "form-control col-md-7 col-xs-12" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <%= f.submit "Update category", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
</div>

app/views/admin/categories/index.html.erb
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>All categories <small>basic</small></h2>

                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <table class="table">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Name Category</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @categories.each do |category| %>
                        <tr>
                          <th scope="row"><%= category.id %></th>
                          <td><%= category.name %></td>
                          <td><%= link_to "edit", edit_admin_category_path(category),
                            method: :get, class: 'btn btn-default' %></td>
                          <td><%= link_to "delete", admin_category_path(category),
                           method: :delete, class: 'btn btn-danger',
                            data: { confirm: "You sure?" } %></td>
                        </tr>

                      <% end %>
                    </tbody>
                    </table>
                  </div>
                </div>
                  <%= will_paginate @categories %>
              </div>
        </div>

app/views/admin/categories/new.html.erb
         <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Category <small>new</small></h2>
                   <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <%= form_for(@category,url: admin_categories_path,  html: {class: "form-horizontal form-label-left"}) do |f| %>
                      <%= render 'shared/error_messages', object: f.object %>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >Name <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :name, class: "form-control col-md-7 col-xs-12" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <%= f.submit "Create new category", class: "btn btn-primary" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
         </div>