config/routes.rb
Rails.application.routes.draw do

  namespace :customer do
    resources :sessions
    resources :lessions  do
      collection do
        get :search
      end
    end
    resources :users
    resources :tests do
      member do
        get  :start, :result
        post :finnish
      end
    end
    resources :sentences, only: [:update]
    resources :staticpage, only: [:index]
  end

  root "customer/staticpage#index"
  get   'login'   => 'sessions#new'
  resources :sessions
  namespace :admin do
    resources :categories
    resources :lessions
    resources :quessions do
      collection do
        get :import_csv
      end
    end
    resources :staticpage, only: [:index]
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :quession

  validates :content,  presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessions, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.max_name}
end

app/models/customer.rb
module Customer
  def self.table_name_prefix
    'customer_'
  end
end

app/models/customer/session.rb
class Customer::Session < ActiveRecord::Base
end

app/models/lession.rb
class Lession < ActiveRecord::Base
  belongs_to :category
  has_many :quessions, dependent: :destroy

  validates :content, presence: true , length: { maximum: Settings.max_content },
    uniqueness: { case_sensitive: false }

  def self.search(condition_search = '')
    if "".eql?(condition_search)
      return Lession.all
    else
      return Lession.where("content like ?", "%#{condition_search}%")
    end
  end
end

app/models/quession.rb
class Quession < ActiveRecord::Base
  belongs_to :lession

  # has_many :sentences, dependent: :destroy
  validates :lession, presence: true
  validates :content, presence: true

  has_many :answers , dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  # validates_associated :answers
  validate :must_have_correct_checked

  # def self.search(user_id, category_id = '' ,condition_search = '')
  #   lession_ids = "select id from lessions where user_id = #{user_id}"
  #   word_ids = "select word_id from quessions where lession_id in (#{lession_ids})"
  #   if "learned".eql?(condition_search)
  #     return ''.eql?(category_id) ? Word.where("id in (#{word_ids})") :
  #     Word.where("id in (#{word_ids}) and category_id = #{category_id}")
  #   elsif "unlearned".eql?(condition_search)
  #     return ''.eql?(category_id) ? Word.where("id not in (#{word_ids})") :
  #     Word.where("id not in (#{word_ids}) and category_id = #{category_id}")
  #   else
  #     return ''.eql?(category_id) ? Word.all : Word.where("category_id = #{category_id}")
  #   end
  # end

  def import file
       CSV.foreach(file.path, headers: true, col_sep: "|", header_converters: :symbol) do |row|
         row = row.to_hash
         answers_attributes = []
         row[:answers].split(";").each do |answer|
           answer_hash = Hash.new
           arr_answer = answer.split(",")
           answer_hash[:content] = arr_answer[0]
           answer_hash[:is_correct] = arr_answer[1]
           answers_attributes.push answer_hash
         end
         row[:answers_attributes] = answers_attributes
         row.delete :answers
         Question.create! row
       end
  end

  def meaning
    self.answers.each do |answer|
      if answer.is_correct
        return answer.content
      end
    end
    return "can't find"
  end

  private
    def must_have_correct_checked
      self.answers.each do |answer|
        if answer.is_correct
          return true
        end
      end
      errors.add(:is_correct,"must have correct answer!!!")
    end
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :test, dependent: :destroy
  belongs_to :quession
  belongs_to :answer
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :user
  belongs_to :lession

  has_many :sentences, dependent: :destroy

  accepts_nested_attributes_for :sentences
  default_scope -> { order(created_at: :desc) }
  # validates_associated :sentences

  def result
    count = 0
    self.sentences.each do |_sentence|
      if !_sentence.answer.nil? && _sentence.answer.is_correct
        count += 1
      end
    end
    return count
  end

  def make_random_questions(lession_id = "")
     if "".eql?(lession_id)
      quessions = Quession.order("RANDOM()").limit(Settings.number_of_quession)
     else
      quessions = Quession.where(lession_id: lession_id).order("RANDOM()").
        limit(Settings.number_of_quession)
     end
      quessions.each do |quession|
        self.sentences.create(quession_id: quession.id)
      end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :tests, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :requests, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.max_name}
  validates :email, presence: true,
    length: {maximum: Settings.max_email},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.mini_password}, allow_nil: true

  has_secure_password

  before_save :downcase_email

  def downcase_email
   self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && (@user.authenticate params[:session][:password])
      log_in @user
      redirect_back_or root_url
    else
      flash.now[:danger] = Settings.invalid_login
      render :new
    end

  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/lessions_helper.rb
module Admin::LessionsHelper
end

app/helpers/admin/quessions_helper.rb
module Admin::QuessionsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/customer/tests_helper.rb
module Customer::TestsHelper
end

app/helpers/customer/user_helper.rb
module Customer::UserHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user? user
    user == current_user
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "please loggin"
      redirect_to login_url
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/layouts/_admin_footer.html.erb
<div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
</div>
</html>
    <script src="/assets/admin/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/assets/admin/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/assets/admin/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/assets/admin/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/assets/admin/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="/assets/admin/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="/assets/admin/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="/assets/admin/vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="/assets/admin/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="/assets/admin/vendors/Flot/jquery.flot.js"></script>
    <script src="/assets/admin/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="/assets/admin/vendors/Flot/jquery.flot.time.js"></script>
    <script src="/assets/admin/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="/assets/admin/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/assets/admin/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="/assets/admin/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="/assets/admin/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/assets/admin/vendors/DateJS/build/date.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="/assets/admin/build/js/custom.min.js"></script>

app/views/layouts/_admin_header.html.erb
<%= render "layouts/admin_library" %>

<div class="col-md-3 left_col">
        <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="#" class="site_title"><i class="fa fa-paw"></i> <span>Ruby Admin</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="/assets/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2><%= current_user.name unless current_user.nil?  %></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />
            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="index.html">Dashboard</a></li>
                      <li><a href="index2.html">Dashboard2</a></li>
                      <li><a href="index3.html">Dashboard3</a></li>
                    </ul>
                  </li>
                  <li><a href="/users" data-method="get" ><i class="fa fa-edit"></i> User <span class="fa fa-chevron-down"></span></a>
                  </li>
                  <li><a><i class="fa fa-desktop"></i> Categories <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to "Manage Categories", admin_categories_path, method: :get %></li>
                      <li><%= link_to "New Category",  new_admin_category_path, method: :get %></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-table"></i> Lessions <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to "Manage Lession", admin_lessions_path, method: :get %></li>
                      <li><%= link_to "New Lession",  new_admin_lession_path, method: :get %></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-table"></i> Quessions <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to "Manage Quessions", admin_quessions_path, method: :get %></li>
                      <li><%= link_to "New Quessions",  new_admin_quession_path, method: :get %></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-bar-chart-o"></i> Products <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to "Manage Products", "#", method: :get %></li>
                      <li><%= link_to "New Product",  "#", method: :get %></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                      <li><a href="fixed_footer.html">Fixed Footer</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
              <div class="menu_section">
                <h3>Live On</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="e_commerce.html">E-commerce</a></li>
                      <li><a href="projects.html">Projects</a></li>
                      <li><a href="project_detail.html">Project Detail</a></li>
                      <li><a href="contacts.html">Contacts</a></li>
                      <li><a href="profile.html">Profile</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="page_403.html">403 Error</a></li>
                      <li><a href="page_404.html">404 Error</a></li>
                      <li><a href="page_500.html">500 Error</a></li>
                      <li><a href="plain_page.html">Plain Page</a></li>
                      <li><a href="login.html">Login Page</a></li>
                      <li><a href="pricing_tables.html">Pricing Tables</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
        </div>
            <!-- /sidebar menu -->
</div>

app/views/layouts/_admin_library.html.erb
    <!-- Bootstrap -->
    <link href="/assets/admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/assets/admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/assets/admin/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="/assets/admin/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="/assets/admin/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="/assets/admin/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="/assets/admin/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/assets/admin/build/css/custom.min.css" rel="stylesheet">

app/views/layouts/_admin_topnavigation.html.erb
<div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="/assets/img.jpg" alt=""><%= current_user.name unless current_user.nil?  %>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="/assets/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="/assets/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>

app/views/layouts/_footer.html.erb
<div id="footer" data-animate="fadeInUp">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6">
        <h4><%= t "more" %></h4>
        <ul>
          <li><a href="#"><%= t "about" %></a></li>
          <li><a href="#"><%= t "termsandconditions" %></a></li>
          <li><a href="#"><%= t "faq" %></a></li>
          <li><a href=#><%= t "contact" %></a></li>
        </ul>
        <hr>
        <h4><%= t "user_section" %></h4>
        <hr class="hidden-md hidden-lg hidden-sm">
      </div>
      <div class="col-md-4 col-sm-6">
        <h4><%= t "getnew" %></h4>
        <p class="text-muted"><%= t "email" %></p>
        <form>
          <div class="input-group">
            <input type="text" class="form-control">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button"><%= t "commit" %>
              </button>
            </span>
          </div>
        </form>
        <hr>
          <p class="social">
            <a href="#" class="facebook external" data-animate-hover="shake">
              <i class="fa fa-facebook"></i></a>
            <a href="#" class="twitter external" data-animate-hover="shake">
              <i class="fa fa-twitter"></i></a>
            <a href="#" class="instagram external" data-animate-hover="shake">
              <i class="fa fa-instagram"></i></a>
            <a href="#" class="gplus external" data-animate-hover="shake">
              <i class="fa fa-google-plus"></i></a>
            <a href="#" class="email external" data-animate-hover="shake">
              <i class="fa fa-envelope"></i></a>
          </p>
      </div>
    </div>
  </div>
</div>
<div id="copyright">
  <div class="container">
    <div class="col-md-6">
      <p class="pull-left">©<%= t "company" %></p>
    </div>
    <div class="col-md-6">
      <p class="pull-right">
        <a href="https://bootstrapious.com/e-commerce-templates" >
        </a><%= t "bootstrap" %></p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="top">
  <div class="container">
    <div class="col-md-6 offer" data-animate="fadeInDown">
      <a href="#" class="btn btn-success btn-sm" data-animate-hover="shake">
        <%= t "offer" %></a>
      <a href="#"><%= t "orders_off" %></a>
    </div>
    <div class="col-md-6" data-animate="fadeInDown">
      <ul class="menu">
        <% if logged_in? %>
          <li><%= link_to t("profile"), customer_user_path(current_user), method: :get %></li>
          <li><%= link_to t("setting"), edit_customer_user_path(current_user) %></li>
          <li><%= link_to t("logout"), customer_session_path(current_user),
            method: :delete %></li>
        <% else %>
          <li><a href="#" data-toggle="modal" data-target="#login-modal">
            <%= t "login" %></a></li>
          <li><%= link_to t("register"), new_customer_user_path, method: :get %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="modal fade" id="login-modal" tabindex="-1"
    role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="Login"><%= t "login" %></h4>
        </div>
        <div class="modal-body">
        <%= form_for(:session, url: customer_sessions_path) do |f| %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control",
              placeholder: "email" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= link_to t("forget_password"), "#" %>
            <%= f.password_field :password, class: "form-control",
              placeholder: "password" %>
          </div>
          <div class="form-group">
            <%= f.submit t("login"), class: "btn btn-primary" %>
          </div>
        <% end %>
        <p class="text-center text-muted"><%= t "not_registered" %></p>
        <p class="text-center text-muted"><%= link_to t("register"), new_customer_user_path %>
          </a><%= t "easy_access_comment" %></p>
        </div>
      </div>
    </div>
  </div>
</div>


    <div class="navbar navbar-default yamm" role="navigation" id="navbar">
        <div class="container">
          <!-- logo -->

            <div class="navbar-header">
                <a class="navbar-brand home" href="index" data-animate-hover="bounce">
                    <img src="/assets/logo.png" height="50" width="139" alt="Obaju logo" class="hidden-xs">
                </a>
            </div>
            <!--/.navbar-header -->


            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-left">
                    <li><%= link_to "Trang Chủ", root_path %></li>
                    <% Category.all.each do |category|  %>
                      <li class="dropdown yamm-fw">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200"><%= category.name %><b class="caret"></b></a>
                          <ul class="dropdown-menu">
                              <li>
                                  <div class="yamm-content">
                                      <div class="row">
                                        <% category.lessions.each do |lession|  %>
                                          <div class="col-sm-4">
                                              <ul><li><%= link_to lession.name, customer_lession_path(lession) %></a></li>
                                              </ul>
                                          </div>
                                        <% end %>

                                      </div>
                                  </div>
                                  <!-- /.yamm-content -->
                              </li>
                          </ul>
                      </li>
                    <% end %>
                </ul>
            </div>
            <div class="navbar-buttons">

                <div class="navbar-collapse collapse right" id="basket-overview">
                    <%= link_to "Result", customer_tests_path, class: "btn btn-primary navbar-btn", method: :get %>
                </div>
                <!--/.nav-collapse -->

                <div class="navbar-collapse collapse right" id="search-not-mobile">
                    <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                        <span class="sr-only">Toggle search</span>
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
            <div class="collapse clearfix" id="search">
                <%= form_for(:search_form, url: search_customer_lessions_path ,method: :get, remote: true, html:{ class: "navbar-form", role: "search"} ) do |f | %>
                  <div class="input-group">
                    <%= f.text_field :condition, class: "form-control", placeholder: "Search" %>
                    <span class="input-group-btn">
                       <%= f.button '<i class="fa fa-search"></i>'.html_safe , class: 'btn btn-primary', onclick: "this.form.submit();" %>
                    </span>
                  </div>
                <% end %>
            </div>
        </div>
        <!-- /.container -->
    </div>

app/views/layouts/_right_navbar.html.erb
                <div class="col-md-3">
                    <!-- *** MENUS AND FILTERS ***
 _________________________________________________________ -->
                    <div class="panel panel-default sidebar-menu">

                        <div class="panel-heading">
                            <h3 class="panel-title">Bài Biết mới nhất</h3>
                        </div>

                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked category-menu">
                                <% Category.all.each do |category|  %>
                                <li>
                                    <a href="category.html"><%= category.name  %><span class="badge pull-right"></span></a>
                                    <% category.lessions.limit(10).order(created_at: :desc).each do |lession|  %>
                                    <ul>
                                        <li><%= link_to lession.name, customer_lession_path(lession) %></a></li>
                                    </ul>
                                    <% end %>
                                </li>
                                <% end %>
                            </ul>

                        </div>
                    </div>
            </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <%= render "layouts/admin_header" %>
      <%= render "layouts/admin_topnavigation" %>
      <!-- page content -->
      <div class="right_col" role="main">
          <%= yield %>
      </div>
    </div>
  <%= render "layouts/admin_footer" %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t "project_name" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="all">
    <div id="content">
      <div class="container">
      <%= render "layouts/right_navbar" %>
      <%= yield %>
      </div>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.present? && object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>